CREATE TABLE CUSTOMERS( 
   ID   INT NOT NULL, 
   NAME VARCHAR (20) NOT NULL, 
   AGE INT NOT NULL, 
   ADDRESS CHAR (25), 
   SALARY   DECIMAL (18, 2),        
   PRIMARY KEY (ID) 
);  
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY) 
VALUES (1, 'UMAIR SAAD', 21, 'DIGRI', 0.00 );  

DECLARE
  C_ID CUSTOMERS.ID%TYPE := 1;
  C_NAME CUSTOMERS.NAME%TYPE;
BEGIN
  SELECT ID, NAME INTO C_ID, C_NAME FROM CUSTOMERS WHERE ID = C_ID;
  DBMS_OUTPUT.PUT_LINE(C_NAME || ', ' || C_ID);
END;
/
